id: PA32E4AA9
initial_creation_type: input
source_metadata:
  title: Nyoshul Khenpo Jamyang Dorje
  language: de
  description: 'Texts by the great Dzogchen teacher and historian Nyoshul Khenpo Jamyang
    Dorje (smyo shul mkhan po ''jam dbyangs rdo rje, 1932–1999):'
  volume:
    a630c51c12b24d759dd792f8bb5506e4:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Calling the Guru from Afar
    b8897be503704958a913321eb1cb0ebc:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    85bbc7a35200442fa0629f8951d1f068:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Dzogchen
    ab9cec5e45ad45d99aa1b91db5a7d06c:
      title: The Five Wisdoms
      parent: Dzogchen
    7dbafe92001242f4adfcb930972a014f:
      title: Prayer to the Omniscient Longchen Rabjam
      parent: Lineage Prayers
    4185f61d86574cc38f0067ea0d780ceb:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Poems
    facd9a5a38814108a8e7fada48915434:
      title: Natural Great Peace
      parent: Poems
created_at: '2022-03-01T01:05:41.715846'
last_modified_at: '2022-03-01T01:05:41.715849'
